version: '3.8'

services:
  auth-sso-service:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge